services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LITELLM_BASE_URL=${LITELLM_BASE_URL}
      - LITELLM_API_KEY=${LITELLM_API_KEY}
    restart: unless-stopped
    networks:
      - agno_network

networks:
  agno_network:
    driver: bridge